# Docker Compose configuration for VPS Automation Server - Simplified

version: '3.8'

services:
  # Main FastAPI application
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    container_name: vps-automation-web
    restart: unless-stopped
    ports:
      - "8080:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
      - DISPLAY=:99
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - app_logs:/app/logs
      - app_tmp:/app/tmp
      # Shared memory for browsers
      - /dev/shm:/dev/shm
      # X11 display support for visible browser automation
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /var/run/dbus:/var/run/dbus:ro
    networks:
      - vps_automation_network
    command: ["python", "-m", "uvicorn", "app.main_production:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    security_opt:
      - no-new-privileges:true
    mem_limit: 4g
    cpus: '2.0'
    # Allow access to X11 display
    privileged: false
    ipc: host

  # Redis for data storage and caching
  redis:
    image: redis:7-alpine
    container_name: vps-automation-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --appendonly yes 
      --appendfsync everysec
      --maxmemory 1gb
      --maxmemory-policy allkeys-lru
      --tcp-keepalive 60
      --timeout 300
    volumes:
      - redis_data:/data
    networks:
      - vps_automation_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    security_opt:
      - no-new-privileges:true
    mem_limit: 1g
    cpus: '0.5'

# Named volumes for persistence
volumes:
  redis_data:
    driver: local
  app_logs:
    driver: local
  app_tmp:
    driver: local

# Custom network for service communication
networks:
  vps_automation_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 